events{
    worker_connections 1024;
}

http {
    server {
        
        listen 80;

        server_name 35.180.190.131;

        location / {
            
            proxy_pass http://35.180.190.131:4000;
            
            # Transmet le nom de domaine original au serveur Phoenix
            proxy_set_header Host $host;
            
            # Transmet l'IP réelle du client (sinon Phoenix verra l'IP de Nginx)
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Définit le protocole (utile si tu utilises HTTPS plus tard)
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}