server {   
    listen 80;
    server_name badge.reader.yggdrasil.colint.school;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name badge.reader.yggdrasil.colint.school;

    ssl_certificate /etc/letsencrypt/live/badge.reader.yggdrasil.colint.school/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/badge.reader.yggdrasil.colint.school/privkey.pem;

    location / {
        
        proxy_pass http://localhost:4000;
        
        # Transmet le nom de domaine original au serveur Phoenix
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        
        # Transmet l'IP réelle du client (sinon Phoenix verra l'IP de Nginx)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Définit le protocole (utile si tu utilises HTTPS plus tard)
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
