server {   
    listen 80;
    server_name badge.reader.yggdrasil.colint.school;

    location / {
        
        proxy_pass http://web:4000;
        
        # Transmet le nom de domaine original au serveur Phoenix
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        
        # Transmet l'IP réelle du client (sinon Phoenix verra l'IP de Nginx)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Définit le protocole (utile si tu utilises HTTPS plus tard)
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
