name: cd_badge_reader

on:
    push:
        branches: ["main"]

jobs:
    production:
        runs-on: ubuntu-latest

        steps:

            - name: Ecriture shh key
              run: |
                echo "${{ secrets.SSH_KEY_AWS }}" > key.pem
                chmod 400 key.pem

            - name: ajoute Ec2 aux known_hosts
              run: |
                mkdir -p ~/.ssh
                touch ~/.ssh/known_hosts
                chmod 644 ~/.ssh/known_hosts
                ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
                
            - name: Conection Ec2
              run: |
                ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "echo connection ok"

            - name: arret docker
              run: docker-compose down

            - name: Suppression des volumes
              run: docker system prune -a --volumes

            - name: pull image docker
              run: docker pull theoden714/badge_reader:latest

            - name: mise en route
              run: docker-compose up

            - name: sortir d'Ec2
              run: exit

            - name: Supression de la clef
              run: rm -f key.pem