name: test_action

on:
    push:
        branches: ["develop"]
    
    pull_request:
        branches: ["main", "develop"] 

jobs:
    elixir_ci:
        runs-on: ubuntu-latest
    
        steps:
            - name: Clonage du repo
              uses: actions/checkout@v4

            - name: Instalation d'Elixir et Erlan
              uses: erlef/setup-beam@v1
              with:
                elixir-version: '1.18' 
                otp-version: '27'
            
            - name: Installation des dépendances Mix
              working-directory: ./badge_reader
              run: mix deps.get

            - name: Compilation elixir
              working-directory: ./badge_reader  
              run: mix compile
    
    build_and_push_image:
        runs-on: ubuntu-latest
        
        needs: elixir_ci

        steps:
            - name: Clonage du repo
              uses: actions/checkout@v4
          
            - name: Installation docker
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.LOGIN }}
                password: ${{ secrets.PASSWORD }}

            - name: Build & Push
              uses: docker/build-action@v5
              with:
                context: ./badge_reader
                push: true
                tags: ${{ secrets.LOGIN}}/badge_reader:latest