name: test_action

on:
    push:
        branches: ["develop"]
    
    pull_request:
        branches: ["main", "develop"] 

jobs:
    elixir_ci:
        runs-on: ubuntu-latest
    
        steps:
            - name: Clonage du repo
              uses: actions/checkout@v6

            - name: Instalation d'Elixir et Erlan
              uses: erlef/setup-beam@v1
              with:
                elixir-version: '1.18' 
                otp-version: '27'
            
            - name: Installation des dépendances Mix
              working-directory: ./badge_reader
              env:
                MIX_ENV: test
              run: |
                mix local.hex --force
                mix local.rebar --force
                mix deps.get

            - name: Compilation elixir
              working-directory: ./badge_reader  
              env:
                MIX_ENV: test
              run: mix compile

            - name: Test de qualité
              working-directory: ./badge_reader  
              env:
                MIX_ENV: test
              run: mix quality
    
    build_and_push_image:
        runs-on: ubuntu-latest
        
        needs: elixir_ci

        steps:
            - name: Clonage du repo
              uses: actions/checkout@v6
          
            - name: Installation docker
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.LOGIN }}
                password: ${{ secrets.PASSWORD }}

            - name: Build & Push
              uses: docker/build-push-action@v6
              with:
                context: ./badge_reader
                push: true
                tags: ${{ secrets.LOGIN }}/badge_reader:latest